### ISSUE TITLE
Problem when activating MN in Mac OS HIGH Sierra Wallet

### ISSUE THREAD

**Issue by jadefalke** [VolixNetwork/Volix#1]
if I hit start missing Masternodes I get this Error Message:
<img width="385" alt="image" src="https://user-images.githubusercontent.com/44189884/47106331-8c687600-d246-11e8-8452-ad12876dac78.png">

activating via Debug Consol works without Problems.

<img width="787" alt="image" src="https://user-images.githubusercontent.com/44189884/47106199-47dcda80-d246-11e8-9e55-38b9c2b39c39.png">

**Comment by VolixNetwork** [comment]
Fixed by releasing a new Mac OS High sierra wallet.
